[log]
enabled = true
log_level = "debug"

[manager]
linemode = "size_and_mtime"
show_hidden = true
show_symlinks = true
sort_by = "mtime"
sort_dir_first = false
sort_reverse = true

[opener]

play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" },
]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
  { run = "%EDITOR% %*", block = true, for = "windows" },
]

open = [{ run = 'xdg-open "$@"', desc = "Open" }]

extract = [
  { run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

prepend_previewers = [
  { name = "*.csv", run = "rich-preview" },   # for csv files
  { name = "*.md", run = "glow" },            # for markdown (.md) files
  { name = "*.rst", run = "rich-preview" },   # for restructured text (.rst) files
  { name = "*.ipynb", run = "rich-preview" }, # for jupyter notebooks (.ipynb)
  { name = "*.json", run = "rich-preview" },  # for json (.json) files
  # { name = "*.", run = "rich-preview"} # for particular language files eg. .py, .go., .lua, etc.
]


# [[plugin.prepend_previewers]]
# name = "*.md"
# run = "glow"
#
# [[plugin.prepend_previewers]]
# mime = "audio/*"
# run = "exifaudio"
#
# [[plugin.prepend_previewers]]
# name = "*.csv"
# run = "rich-preview"
#
# [[plugin.prepend_previewers]]
# name = "*.rst"
# run = "rich-preview"
#
# [[plugin.prepend_previewers]]
# name = "*.ipynb"
# run = "rich-preview"
#
# [[plugin.prepend_previewers]]
# name = "*.json"
# run = "rich-preview"

[[previewers.prepend]]
mime = "application/zip"
run = "ouch"

[[previewers.prepend]]
mime = "application/tar"
run = "ouch"

[[previewers.prepend]]
mime = "application/bzip2"
run = "ouch"

[[previewers.prepend]]
mime = "application/7z-compressed"
run = "ouch"

[[previewers.prepend]]
mime = "application/rar"
run = "ouch"

[[previewers.prepend]]
mime = "application/xz"
run = "ouch"
